mybatis:
    mapper-locations: classpath:mapper/*xml
    type-aliases-package: com.java.zero.entity
spring:
    application:
        name: java-zero-mybatis
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        name: defaultDataSource
        password: 12345678
        url: jdbc:mysql://localhost:3306/middlewares?serverTimezone=UTC
        username: root
