mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.li.multithread.mybatis.entity
server:
  port: 8080
spring:
  application:
    name: multi-thread
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/java_zero?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&failOverReadOnly=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true