spring:
    application:
        name: spring-file-storage
    file-storage:
        local-plus:
            - platform: local-plus-1 # 存储平台标识
              enable-storage: true  #启用存储
              enable-access: true #启用访问（线上请使用 Nginx 配置，效率更高）
              domain: "http://127.0.0.1:20001/" # 访问域名，例如：“http://127.0.0.1:8030/”，注意后面要和 path-patterns 保持一致，“/”结尾，本地存储建议使用相对路径，方便后期更换域名
              base-path: local-plus/ # 基础路径
              path-patterns: /** # 访问路径
              storage-path: D:/Temp/ # 存储路径
    servlet:
      multipart:
        max-file-size: 50MB
        max-request-size: 50MB
server:
    port: 20001
